import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { KijiItems } from '../KijiItems';
import { KijiItem } from '../KijiItem';
import { Observable } from 'rxjs';
import { map , tap} from 'rxjs/operators';



@Injectable()
export class LinkColRetrieveService {

    private icons = [
        'add-circle-outline',
        'add-circle',
        'add',
        'airplane',
        'alarm',
        'albums',
        'alert',
        'american-football',
        'analytics',
        'aperture',
        'apps',
        'appstore',
        'archive',
        'arrow-back',
        'arrow-down',
        'arrow-dropdown-circle',
        'arrow-dropdown',
        'arrow-dropleft-circle',
        'arrow-dropleft',
        'arrow-dropright-circle',
        'arrow-dropright',
        'arrow-dropup-circle',
        'arrow-dropup',
        'arrow-forward',
        'arrow-round-back',
        'arrow-round-down',
        'arrow-round-forward',
        'arrow-round-up',
        'arrow-up',
        'at',
        'attach',
        'backspace',
        'barcode',
        'baseball',
        'basket',
        'basketball',
        'battery-charging',
        'battery-dead',
        'battery-full',
        'beaker',
        'bed',
        'beer',
        'bicycle',
        'bluetooth',
        'boat',
        'body',
        'bonfire',
        'book',
        'bookmark',
        'bookmarks',
        'bowtie',
        'briefcase',
        'browsers',
        'brush',
        'bug',
        'build',
        'bulb',
        'bus',
        'business',
        'cafe',
        'calculator',
        'calendar',
        'call',
        'camera',
        'car',
        'card',
        'cart',
        'cash',
        'cellular',
        'chatboxes',
        'chatbubbles',
        'checkbox-outline',
        'checkbox',
        'checkmark-circle-outline',
        'checkmark-circle',
        'checkmark',
        'clipboard',
        'clock',
        'close-circle-outline',
        'close-circle',
        'close',
        'cloud-circle',
        'cloud-done',
        'cloud-download',
        'cloud-outline',
        'cloud-upload',
        'cloud',
        'cloudy-night',
        'cloudy',
        'code-download',
        'code-working',
        'code',
        'cog',
        'color-fill',
        'color-filter',
        'color-palette',
        'color-wand',
        'compass',
        'construct',
        'contact',
        'contacts',
        'contract',
        'contrast',
        'copy',
        'create',
        'crop',
        'cube',
        'cut',
        'desktop',
        'disc',
        'document',
        'done-all',
        'download',
        'easel',
        'egg',
        'exit',
        'expand',
        'eye-off',
        'eye',
        'fastforward',
        'female',
        'filing',
        'film',
        'finger-print',
        'fitness',
        'flag',
        'flame',
        'flash-off',
        'flash',
        'flashlight',
        'flask',
        'flower',
        'folder-open',
        'folder',
        'football',
        'funnel',
        'gift',
        'git-branch',
        'git-commit',
        'git-compare',
        'git-merge',
        'git-network',
        'git-pull-request',
        'glasses',
        'globe',
        'grid',
        'hammer',
        'hand',
        'happy',
        'headset',
        'heart-dislike',
        'heart-empty',
        'heart-half',
        'heart',
        'help-buoy',
        'help-circle-outline',
        'help-circle',
        'help',
        'home',
        'hourglass',
        'ice-cream',
        'image',
        'images',
        'infinite',
        'information-circle-outline',
        'information-circle',
        'information',
        'jet',
        'journal',
        'key',
        'keypad',
        'laptop',
        'leaf',
        'link',
        'list-box',
        'list',
        'locate',
        'lock',
        'log-in',
        'log-out',
        'magnet',
        'mail-open',
        'mail-unread',
        'mail',
        'male',
        'man',
        'map',
        'medal',
        'medical',
        'medkit',
        'megaphone',
        'menu',
        'mic-off',
        'mic',
        'microphone',
        'moon',
        'more',
        'move',
        'musical-note',
        'musical-notes',
        'navigate',
        'notifications-off',
        'notifications-outline',
        'notifications',
        'nuclear',
        'nutrition',
        'open',
        'options',
        'outlet',
        'paper-plane',
        'paper',
        'partly-sunny',
        'pause',
        'paw',
        'people',
        'person-add',
        'person',
        'phone-landscape',
        'phone-portrait',
        'photos',
        'pie',
        'pin',
        'pint',
        'pizza',
        'planet',
        'play-circle',
        'play',
        'podium',
        'power',
        'pricetag',
        'pricetags',
        'print',
        'pulse',
        'qr-scanner',
        'quote',
        'radio-button-off',
        'radio-button-on',
        'radio',
        'rainy',
        'recording',
        'redo',
        'refresh-circle',
        'refresh',
        'remove-circle-outline',
        'remove-circle',
        'remove',
        'reorder',
        'repeat',
        'resize',
        'restaurant',
        'return-left',
        'return-right',
        'reverse-camera',
        'rewind',
        'ribbon',
        'rocket',
        'rose',
        'sad',
        'save',
        'school',
        'search',
        'send',
        'settings',
        'share-alt',
        'share',
        'shirt',
        'shuffle',
        'skip-backward',
        'skip-forward',
        'snow',
        'speedometer',
        'square-outline',
        'square',
        'star-half',
        'star-outline',
        'star',
        'stats',
        'stopwatch',
        'subway',
        'sunny',
        'swap',
        'switch',
        'sync',
        'tablet-landscape',
        'tablet-portrait',
        'tennisball',
        'text',
        'thermometer',
        'thumbs-down',
        'thumbs-up',
        'thunderstorm',
        'time',
        'timer',
        'today',
        'train',
        'transgender',
        'trash',
        'trending-down',
        'trending-up',
        'trophy',
        'tv',
        'umbrella',
        'undo',
        'unlock',
        'videocam',
        'volume-high',
        'volume-low',
        'volume-mute',
        'volume-off',
        'walk',
        'wallet',
        'warning',
        'watch',
        'water',
        'wifi',
        'wine',
        'woman'
      ];
      private subIcons1 = this.icons.slice(1, 30);
      private subIcons2 = this.icons.slice(31, 60);
      private subIcons3 = this.icons.slice(61, 90);
      private subIcons4 = this.icons.slice(91, 120);
      private subIcons5 = this.icons.slice(121, 150);
      private subIcons6 = this.icons.slice(151, 180);
      private subIcons7 = this.icons.slice(181, 210);
      private subIcons8 = this.icons.slice(211, 240);
      private subIcons9 = this.icons.slice(241, 270);
      private subIcons10 = this.icons.slice(271, 300);
      private subIcons11 = this.icons.slice(301);
      private subIdonsList = [
          this.subIcons1,
          this.subIcons2,
          this.subIcons3,
          this.subIcons4,
          this.subIcons5,
          this.subIcons6,
          this.subIcons7,
          this.subIcons8,
          this.subIcons9,
          this.subIcons10,
          this.subIcons11
      ];

    constructor(private http: HttpClient) { }

    public getLinkCol(url: string): Observable<KijiItem[]> {
        const linkColJsonStr: Observable<KijiItems> = this.http.get<KijiItems>(url);
        let linkColStr: Observable<KijiItem[]> = linkColJsonStr.pipe(
            map(linkCollectionJson =>  linkCollectionJson.kijiItems)
        );
        linkColStr = linkColStr.pipe(
            tap(kijiItems =>  kijiItems.forEach(kijiItem => {
                if (!kijiItem.icon) {
                    kijiItem.icon = this.getRandomIcon();
                }
            }))
        );
        return linkColStr;
    }

   private  getRandomIcon() {
        // const idxA = (kijiId as unknown as number) % this.icons.length;
        const subIcons = this.getIcons();
        const idxB = Math.floor(Math.random() * subIcons.length);
        const iconName = subIcons[ idxB ];
       //  console.log( '${idxA}  ${idxB} ★ icon:' + iconName);
        return iconName;
   }

   private getIcons(): string[] {
        const idx = Math.floor(Math.random() * this.subIdonsList.length);
        return this.subIdonsList[idx];
   }

}
